2018-07-04 14:23:03 Log.py[line:15] ERROR 写excel出错，Traceback (most recent call last):
  File "C:/Users/jingyu/test_driven_by_keyword/TestScript/Login163.py", line 48, in <module>
    test_data_file.write_cell_content(id+2,action_slapse_time_col_no,elapse_time)
  File "C:\Users\jingyu\test_driven_by_keyword\Util\Exel.py", line 95, in write_cell_content
    self.workbook.save(self.excel_file_path)
  File "D:\python\lib\site-packages\openpyxl\workbook\workbook.py", line 342, in save
    save_workbook(self, filename)
  File "D:\python\lib\site-packages\openpyxl\writer\excel.py", line 264, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\python\lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 13] Permission denied: u'C:\\Users\\jingyu\\test_driven_by_keyword/TestData/testcase.xlsx'

2018-07-04 14:29:12 Log.py[line:19] INFO 现在操作的Excel表是：更改昵称
2018-07-04 14:29:12 Log.py[line:15] ERROR 写excel出错，Traceback (most recent call last):
  File "C:/Users/jingyu/test_driven_by_keyword/TestScript/basicinfo-rename.py", line 46, in <module>
    result=eval(command_line)
  File "<string>", line 1, in <module>
  File "C:\Users\jingyu\test_driven_by_keyword\Action\Action.py", line 38, in visit_url
    raise e
AttributeError: 'NoneType' object has no attribute 'get'

